CREATE USER SAPINST PASSWORD m9dknnPu NO FORCE_FIRST_PASSWORD_CHANGE;

GRANT CONTENT_ADMIN TO SAPINST;
GRANT AFLPM_CREATOR_ERASER_EXECUTE TO SAPINST WITH ADMIN OPTION;

GRANT CREATE SCHEMA TO SAPINST WITH ADMIN OPTION;
GRANT USER ADMIN TO SAPINST WITH ADMIN OPTION;
GRANT ROLE ADMIN TO SAPINST WITH ADMIN OPTION;
GRANT CATALOG READ TO SAPINST WITH ADMIN OPTION;
GRANT EXPORT TO SAPINST;
GRANT IMPORT TO SAPINST;
GRANT INIFILE ADMIN TO SAPINST;

GRANT CREATE ANY, SELECT ON SCHEMA SYSTEM TO SAPINST;

GRANT SELECT, EXECUTE, DELETE ON SCHEMA _SYS_REPO TO SAPINST WITH GRANT OPTION;

ALTER USER SAPINST DISABLE PASSWORD LIFETIME;